### ISSUE TITLE
pip install breaks on pyatomdb v0.10.5

### ISSUE THREAD

**Issue by eblur** [AtomDB/pyatomdb#24]
Hi, I was doing a fresh install on a different computer and noticed a bug with the latest PyPI version

```
$ pip install pyatomdb
pip install pyatomdb
Collecting pyatomdb
  Downloading pyatomdb-0.10.5.tar.gz (19.4 MB)
     |████████████████████████████████| 19.4 MB 437 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /opt/anaconda3/envs/pyxsis-dev/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/x8/jdxp073s3kq6r1m5v1c0lwsw0000gn/T/pip-install-rnmvj7q8/pyatomdb/setup.py'"'"'; __file__='"'"'/private/var/folders/x8/jdxp073s3kq6r1m5v1c0lwsw0000gn/T/pip-install-rnmvj7q8/pyatomdb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/x8/jdxp073s3kq6r1m5v1c0lwsw0000gn/T/pip-pip-egg-info-62gbrigu
         cwd: /private/var/folders/x8/jdxp073s3kq6r1m5v1c0lwsw0000gn/T/pip-install-rnmvj7q8/pyatomdb/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/x8/jdxp073s3kq6r1m5v1c0lwsw0000gn/T/pip-install-rnmvj7q8/pyatomdb/setup.py", line 22, in <module>
        readme = open('README.txt', 'r')
    FileNotFoundError: [Errno 2] No such file or directory: 'README.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

If I fix it to version 0.10.3, it works fine:
```
$ pip install pyatomdb==0.10.3
Collecting pyatomdb==0.10.3
  Downloading pyatomdb-0.10.3.tar.gz (19.4 MB)
     |████████████████████████████████| 19.4 MB 20.3 MB/s 
Collecting requests
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting wget
  Using cached wget-3.2.zip (10 kB)
Requirement already satisfied: numpy>=1.9.0 in /opt/anaconda3/envs/pyxsis-dev/lib/python3.8/site-packages (from pyatomdb==0.10.3) (1.19.1)
Requirement already satisfied: scipy in /opt/anaconda3/envs/pyxsis-dev/lib/python3.8/site-packages/scipy-1.5.2-py3.8-macosx-10.9-x86_64.egg (from pyatomdb==0.10.3) (1.5.2)
Collecting joblib
  Downloading joblib-0.16.0-py3-none-any.whl (300 kB)
     |████████████████████████████████| 300 kB 35.3 MB/s 
Collecting mock
  Downloading mock-4.0.2-py3-none-any.whl (28 kB)
Requirement already satisfied: astropy in /opt/anaconda3/envs/pyxsis-dev/lib/python3.8/site-packages (from pyatomdb==0.10.3) (4.0.1.post1)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/envs/pyxsis-dev/lib/python3.8/site-packages (from requests->pyatomdb==0.10.3) (2020.6.20)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 34.7 MB/s 
Building wheels for collected packages: pyatomdb, wget
  Building wheel for pyatomdb (setup.py) ... done
  Created wheel for pyatomdb: filename=pyatomdb-0.10.3-cp38-cp38-macosx_10_9_x86_64.whl size=154994 sha256=f90963b5f7e0469dc4b8eb7a706e194d6553e677ed606028b6fa3c7fdea891af
  Stored in directory: /Users/lia/Library/Caches/pip/wheels/ba/e1/84/71c8d44e1c4a484d9313c06c5a8f28573100dc9f8d52e61f19
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9681 sha256=5d96f60a68e50aeb12fbeebf6af0184119a727c96fed044b9caf6f1efd493ad9
  Stored in directory: /Users/lia/Library/Caches/pip/wheels/bd/a8/c3/3cf2c14a1837a4e04bd98631724e81f33f462d86a1d895fae0
Successfully built pyatomdb wget
Installing collected packages: idna, chardet, urllib3, requests, wget, joblib, mock, pyatomdb
Successfully installed chardet-3.0.4 idna-2.10 joblib-0.16.0 mock-4.0.2 pyatomdb-0.10.3 requests-2.24.0 urllib3-1.25.10 wget-3.2
```

**Comment by jagophile** [comment]
OK, this is odd. I will investigate.

**Comment by jagophile** [comment]
I have fixed this - I had renamed README.txt to README.rst so Github would display it more nicely but I forgot about the consequences for installation.
