### ISSUE TITLE
pycurl Intsall Issue

### ISSUE THREAD

**Issue by ltlancas** [AtomDB/pyatomdb#52]
Hi, I'm sorry to raise this since after looking through the Issues it seems like similar problems have come up in the past. I tried installing `pyatomdb` on my Mac using

`pip3 install pyatomdb`

When I enter the python3 REPL I get the following
```
>>> import pyatomdb
$PATH/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
ATOMDB environment variable not set. Set up AtomDB files now? (yes/no/info) [yes]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "$PATH/python/site-packages/pyatomdb/__init__.py", line 44, in <module>
    util.initialize()
  File "$PATH/python/site-packages/pyatomdb/util.py", line 539, in initialize
    import curl
  File "$PATH/python/site-packages/curl/__init__.py", line 7, in <module>
    import sys, pycurl
ImportError: pycurl: libcurl link-time version (7.84.0) is older than compile-time version (8.4.0)`
```

When I try un-installing and re-installing `pycurl`, which seemed to be suggested in the installation directions, nothing seems to change. Any ideas on how to fix this?

**Comment by jagophile** [comment]
Hi,
Sorry I somehow missed this issue when it came in.

I am unable to resolve the PyCURL issues - they just keep coming up in weird and "interesting" ways which are completely beyond my control. I have however now removed all use of PyCURL from the project, so as of version 1.0.5 this isn't an issue any more.
